# Generated by Django 3.2.11 on 2022-01-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_first_name_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Name',
            new_name='name',
        ),
    ]
